# Site
name: "Space Moon"
description: "개인적이지만 사소하지 않은 이야기를 담고 싶습니다"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
permalink: /:year/:month/:day/:title:output_ext
google_analytics: 'UA-131297969-1'
disqus: 'inmoonlight'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Social icons and sharing options
social:
  - icon:	twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon:	facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

# Other
markdown: kramdown
highlighter: rouge