# Site
name: "In Moonlight"
description: "사람을 위한 모델링을 하고 싶은 데이터 사이언티스트이자<br>모든 사람이 각자의 색으로 빛나는 세상을 꿈꾸는 이상주의자"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-46278016-1'
disqus: 'inmoonlight'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge